#!/usr/bin/env python3
"""Render the publication section of README.md from publications.yaml.

    tools/gen.py            rewrite README.md in place
    tools/gen.py --check    exit 1 if README.md is out of sync (used by CI)
    tools/gen.py --bib      additionally refresh leissa.bib from doi.org

publications.yaml is the single source of truth; every badge below is derived
from it.  In particular a DOI is spelled out *once* and used for both the badge
label and the link target, so the two cannot drift apart.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RAW = "https://raw.githubusercontent.com/leissa/leissa/main"

BEGIN = "<!-- BEGIN PUBLICATIONS -- generated by tools/gen.py, do not edit by hand -->"
END = "<!-- END PUBLICATIONS -->"

#: Years older than this are folded into a <details> block.
COLLAPSE_BEFORE = 2020

#: DOI prefix -> (badge alt text, badge label, extra shields parameters).
#: An empty label yields the logo-only idiom used by IEEE and Zenodo.
PUBLISHERS = {
    "10.1145": ("ACM", "ACM", "&logo=acm"),
    "10.1109": ("IEEE", "", "&logo=ieee&labelColor=555&logoSize=auto"),
    "10.1007": ("Springer", "Springer", ""),
    "10.1016": ("Elsevier", "Elsevier", "&logo=elsevier&logoColor=white"),
    "10.1142": ("World Scientific", "World Scientific", ""),
    "10.22028": ("UdS", "⌂ UdS", ""),
}

ZENODO = ("zenodo", "", "&logo=zenodo&logoColor=white&labelColor=555&logoSize=auto")


def esc(text: str) -> str:
    """Escape a shields.io static-badge segment: -- is a dash, __ an underscore, _ a space."""
    out = text.replace("-", "--").replace("_", "__").replace(" ", "_")
    return urllib.parse.quote(out, safe="_-.~:/()!*'")


def badge(alt: str, left: str, right: str | None, color: str, href: str, params: str = "") -> str:
    label = f"{esc(left)}-{esc(right)}-{color}" if right is not None else f"{esc(left)}-{color}"
    return f"[![{alt}](https://img.shields.io/badge/{label}?style=flat-square{params})]({href})"


def doi_badge(doi: str) -> str:
    prefix = doi.split("/", 1)[0]
    alt, label, params = PUBLISHERS[prefix]
    return badge(alt, label, doi, "blue", f"https://doi.org/{doi}", params)


def badges(pub: dict) -> list[str]:
    """Badges for one entry, in the canonical order.

    venue -> PDF -> publisher DOI -> arXiv -> Zenodo -> award -> GitHub -> YouTube -> dblp
    """
    out = []
    if "venue" in pub:
        year = str(pub.get("venue_year", pub["year"]))
        out.append(badge(f"{pub['venue']} {year}", pub["venue"], year, "blue", pub["venue_url"]))
    out.append(badge("PDF", "PDF", None, "grey", f"{RAW}/pdf/{pub['id']}.pdf", "&logo=readthedocs"))
    if "doi" in pub:
        out.append(doi_badge(pub["doi"]))
    if "arxiv" in pub:
        out.append(badge("arXiv", "arXiv", pub["arxiv"], "blue",
                         f"https://doi.org/{pub['arxiv']}", "&logo=arxiv"))
    if "zenodo" in pub:
        alt, label, params = ZENODO
        out.append(badge(alt, label, pub["zenodo"], "blue",
                         f"https://doi.org/{pub['zenodo']}", params))
    for award in pub.get("awards", []):
        alt = award["name"].split(" ", 1)[-1]  # drop the leading emoji
        out.append(badge(alt, award["name"], award["text"], "blue", award["url"]))
    for repo in pub.get("repos", []):
        out.append(badge("GitHub", "GitHub", repo["label"], "blue", repo["url"], "&logo=github"))
    if "youtube" in pub:
        out.append(badge("YouTube", "YouTube", None, "grey", pub["youtube"], "&logo=youtube"))
    if "dblp" in pub:
        out.append(badge("dblp", "dblp", None, "grey",
                         f"https://dblp.uni-trier.de/rec/{pub['dblp']}.html?view=bibtex",
                         "&logo=dblp"))
    return out


def entry(pub: dict) -> str:
    lines = [f"* **{pub['title']}** <br>", f"  {pub['authors']} <br>"]
    lines += [f"  {b}" for b in badges(pub)]
    return "\n".join(lines)


def render(pubs: list[dict]) -> str:
    years = sorted({p["year"] for p in pubs}, reverse=True)
    out = [BEGIN, ""]

    out.append(badge("BibTeX", "BibTeX", f"{len(pubs)} entries", "grey",
                     f"{RAW}/leissa.bib", "&logo=latex"))
    out.append(badge("dblp", "dblp", "05/10957", "blue",
                     "https://dblp.uni-trier.de/pid/05/10957.html", "&logo=dblp"))
    out.append("")
    out.append("**Jump to** " + " · ".join(f"[{y}](#{y})" for y in years))
    out.append("")

    selected = [p for p in pubs if p.get("selected")]
    if selected:
        out.append("### ⭐ Selected")
        out.append("")
        for p in selected:
            venue = f"{p['venue']} {p.get('venue_year', p['year'])}" if "venue" in p else str(p["year"])
            out.append(f"* [**{p['title']}**]({RAW}/pdf/{p['id']}.pdf) — {venue}")
        out.append("")

    for y in years:
        of_year = [p for p in pubs if p["year"] == y]
        out.append(f'<a id="{y}"></a>')  # survives pandoc; GitHub links to it as #<year>
        out.append("")
        out.append(f"### {y}")
        out.append("")
        collapsed = y < COLLAPSE_BEFORE
        if collapsed:
            n = len(of_year)
            out.append("<details>")
            out.append(f"<summary>{n} publication{'s' if n > 1 else ''}</summary>")
            out.append("")
        out.append("\n\n".join(entry(p) for p in of_year))
        out.append("")
        if collapsed:
            out.append("</details>")
            out.append("")

    out.append(END)
    return "\n".join(out).rstrip() + "\n"


def validate(pubs: list[dict]) -> list[str]:
    errors = []
    seen = set()
    for p in pubs:
        where = p.get("id", p.get("title", "?"))
        missing = [key for key in ("id", "title", "authors", "year") if key not in p]
        errors += [f"{where}: missing `{key}`" for key in missing]
        if "id" in missing:
            continue
        if p["id"] in seen:
            errors.append(f"{where}: duplicate id")
        seen.add(p["id"])
        if not (ROOT / "pdf" / f"{p['id']}.pdf").is_file():
            errors.append(f"{where}: pdf/{p['id']}.pdf does not exist")
        if "venue" in p and "venue_url" not in p:
            errors.append(f"{where}: `venue` without `venue_url`")
        if "doi" in p and p["doi"].split("/", 1)[0] not in PUBLISHERS:
            errors.append(f"{where}: unknown DOI prefix {p['doi'].split('/', 1)[0]} "
                          f"-- add it to PUBLISHERS in tools/gen.py")
        for key, prefix in (("arxiv", "10.48550/"), ("zenodo", "10.5281/")):
            if key in p and not p[key].startswith(prefix):
                errors.append(f"{where}: `{key}` should be a {prefix}... DOI, got {p[key]}")
        if "dblp" not in p:
            errors.append(f"{where}: missing `dblp` record key")
    unused = {q.stem for q in (ROOT / "pdf").glob("*.pdf")} - seen
    for u in sorted(unused):
        errors.append(f"pdf/{u}.pdf is not referenced by any entry")
    return errors


def fetch_bibtex(doi: str) -> str:
    req = urllib.request.Request(f"https://doi.org/{doi}",
                                 headers={"Accept": "application/x-bibtex; charset=utf-8"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8").strip()


FIELD = re.compile(r"\s*,?\s*([A-Za-z_]+)\s*=\s*")


def parse_bibtex(rec: str) -> tuple[str, dict[str, str]]:
    """Minimal brace-aware BibTeX reader -- enough for what doi.org hands out."""
    m = re.match(r"\s*@(\w+)\s*\{\s*[^,]*,(.*)\}\s*\Z", rec, re.S)
    if not m:
        raise ValueError(f"cannot parse BibTeX record: {rec[:60]}...")
    kind, body = m.group(1).lower(), m.group(2)
    fields, i = {}, 0
    while (f := FIELD.match(body, i)) is not None:
        name, i = f.group(1).lower(), f.end()
        if body[i] == "{":
            depth, start = 1, i + 1
            i = start
            while i < len(body) and depth:
                depth += (body[i] == "{") - (body[i] == "}")
                i += 1
            value = body[start:i - 1]
        else:
            v = re.match(r"[^,]*", body[i:])
            value, i = v.group(0), i + v.end()
        fields[name] = " ".join(value.split())
    return kind, fields


#: Fields we keep, in the order they are written out.  Everything else
#: (ISSN, keywords, copyright, collection, ...) is dropped as noise.
BIB_FIELDS = ["author", "title", "booktitle", "journal", "series", "school", "volume",
              "number", "pages", "publisher", "address", "year", "month", "doi", "url"]


def bib_entry(pub: dict, kind: str, fields: dict[str, str], key: str, doi: str) -> str:
    # The publishers' metadata mangles non-ASCII author names ("Leiba", "Leisa",
    # "Perard-Gayot"), so authors and title come from publications.yaml instead.
    fields["author"] = " and ".join(a.strip() for a in pub["authors"].split(","))
    # the extra braces keep BibTeX styles from lowercasing MimIR, AnyDSL, SIMD, ...
    fields["title"] = "{" + pub["title"] + "}"
    fields["doi"] = doi
    fields["url"] = f"https://doi.org/{doi}"
    if "pages" in fields:
        fields["pages"] = fields["pages"].replace("\u2013", "--").replace("\u2014", "--")
    kind = pub.get("bibtype", kind)  # doi.org calls a thesis a @misc
    if kind == "phdthesis":
        fields["school"] = fields.pop("publisher", "")
    kept = [(k, fields[k]) for k in BIB_FIELDS if fields.get(k)]
    width = max(len(k) for k, _ in kept)
    lines = [f"@{kind}{{{key},"]
    lines += [f"  {k.ljust(width)} = {{{v}}}," for k, v in kept]
    lines.append("}")
    return "\n".join(lines)


def make_bib(pubs: list[dict]) -> str:
    out = [f"% Publications of Roland Leißa -- {RAW}/leissa.bib",
           "%",
           "% Generated by tools/gen.py from publications.yaml; the records themselves",
           "% come from doi.org content negotiation, with authors and titles taken from",
           f"% publications.yaml.  Last update: {datetime.date.today()}.",
           ""]
    for p in pubs:
        doi = p.get("doi") or p["arxiv"]
        key = p["dblp"].rsplit("/", 1)[-1] if "dblp" in p else p["id"]
        if key.startswith("abs-"):  # dblp's CoRR keys make for poor cite keys
            key = p["id"]
        print(f"  {p['id']:<12} {doi}", file=sys.stderr)
        kind, fields = parse_bibtex(fetch_bibtex(doi))
        out.append(bib_entry(p, kind, fields, key, doi))
        out.append("")
    return "\n".join(out)


def make_cff(pubs: list[dict]) -> str:
    """CITATION.cff -- drives GitHub's "Cite this repository" button."""
    cite = next((p for p in pubs if p.get("cite")), pubs[0])
    authors = []
    for name in cite["authors"].split(","):
        given, _, family = name.strip().rpartition(" ")
        authors.append(f"    - family-names: {family}\n      given-names: {given}")
    doi = cite.get("doi") or cite["arxiv"]
    venue = f"{cite['venue']} {cite.get('venue_year', cite['year'])}" if "venue" in cite else str(cite["year"])
    return f"""# Generated by tools/gen.py from publications.yaml -- do not edit by hand.
# The paper below is the one flagged `cite: true`; it is what GitHub offers
# under "Cite this repository".  leissa.bib holds all {len(pubs)} publications.
cff-version: 1.2.0
message: "Please cite the publication below, or pick the matching entry from leissa.bib."
title: "Roland Leißa: publications"
abstract: "Publication archive of Roland Leißa, Professor for Programming Languages and Compilers at the University of Göttingen."
type: dataset
authors:
  - family-names: Leißa
    given-names: Roland
    orcid: "https://orcid.org/0000-0002-2444-6782"
    affiliation: "University of Göttingen"
repository-code: "https://github.com/leissa/leissa"
url: "https://www.uni-goettingen.de/en/707540.html"
preferred-citation:
  type: article
  title: "{cite['title']}"
  authors:
{chr(10).join(authors)}
  year: {cite["year"]}
  notes: "{venue}"
  doi: "{doi}"
  url: "https://doi.org/{doi}"
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only verify that README.md is up to date")
    ap.add_argument("--bib", action="store_true", help="also regenerate leissa.bib (needs network)")
    args = ap.parse_args()

    pubs = yaml.safe_load((ROOT / "publications.yaml").read_text(encoding="utf-8"))
    pubs.sort(key=lambda p: -p["year"])  # stable: within a year, publications.yaml decides

    if errors := validate(pubs):
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        return 1

    readme_path = ROOT / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    if BEGIN not in readme or END not in readme:
        print(f"error: README.md has no {BEGIN} ... {END} block", file=sys.stderr)
        return 1
    head, rest = readme.split(BEGIN, 1)
    tail = rest.split(END, 1)[1]
    updated = head + render(pubs).rstrip("\n") + tail

    if args.check:
        if updated != readme:
            print("error: README.md is out of sync with publications.yaml; run tools/gen.py",
                  file=sys.stderr)
            return 1
        print(f"README.md is up to date ({len(pubs)} publications)")
    else:
        if updated != readme:
            readme_path.write_text(updated, encoding="utf-8")
            print(f"README.md updated ({len(pubs)} publications)")
        else:
            print(f"README.md already up to date ({len(pubs)} publications)")

    cff_path, cff = ROOT / "CITATION.cff", make_cff(pubs)
    if args.check:
        if not cff_path.is_file() or cff_path.read_text(encoding="utf-8") != cff:
            print("error: CITATION.cff is out of sync with publications.yaml; run tools/gen.py",
                  file=sys.stderr)
            return 1
    else:
        cff_path.write_text(cff, encoding="utf-8")

    if args.bib:
        (ROOT / "leissa.bib").write_text(make_bib(pubs), encoding="utf-8")
        print(f"leissa.bib updated ({len(pubs)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
